name: vagrant tests

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  vagrant:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        boxes:
          # Ubuntu
          - bento/ubuntu-12.04  # ubuntu 12.04
          - ubuntu/trusty64     # ubuntu 14.04
          - ubuntu/xenial64     # ubuntu 16.04
          - ubuntu/bionic64     # ubuntu 18.04
          # - ubuntu/focal64      # ubuntu 20.04
          - ubuntu/jammy64      # ubuntu 22.04
          - ubuntu/kinetic64    # ubuntu 22.10
          - ubuntu/lunar64      # ubuntu 23.04

          # Centos
          - bento/centos-6  # centos 6
          - bento/centos-7  # centos 7
          - bento/centos-8  # centos 8

          # Oracle
          - bento/oracle-6  # oracle 6
          - bento/oracle-7  # oracle 7
          - bento/oracle-8  # oracle 8
          - bento/oracle-9  # oracle 9

          # RHEL (SKIP: synced folders not working)
          # - generic/rhel6  # rhel 6
          # - generic/rhel7  # rhel 7
          # - generic/rhel8  # rhel 8

          # Debian
          - debian/contrib-jessie64   # debian 8
          - debian/contrib-stretch64  # debian 9
          - debian/contrib-buster64   # debian 10
          - debian/bullseye64         # debian 11
          - debian/bookworm64         # debian 12

          # Amazon Linux 2
          - bento/amazonlinux-2  # Amazon Linux 2

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: cache vagrant
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile', './.dev/boxes.yaml') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: cache golang
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: install go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x

      - name: build
        run: |
          BUILD_PATH=./build/linux
          mkdir -p $BUILD_PATH
          GOOS=linux GOARCH=amd64 go build -o ${BUILD_PATH}/memr ./cmd/memr

      - name: vagrant up for ${{ matrix.boxes }}
        run: |
          BOX=${{ matrix.boxes }}
          vagrant up ${BOX/\//-}

      - name: test memr on ${{ matrix.boxes }}
        run: |
          BOX=${{ matrix.boxes }}
          vagrant ssh ${BOX/\//-} -c "rm -rf /vagrant/output.mem && sudo /vagrant/build/linux/memr --local-file /vagrant/output.mem --progress=false"
